### PR TITLE
Wakelock

### LINKED ISSUE #206: New refactoring - Android - Wakelock
Description copied from http://tools.android.com/tips/lint-checks:

```
Wakelock
--------
Summary: Incorrect WakeLock usage

Priority: 9 / 10
Severity: Warning
Category: Performance

Failing to release a wakelock properly can keep the Android device in a high
power mode, which reduces battery life. There are several causes of this, such
as releasing the wake lock in onDestroy() instead of in onPause(), failing to
call release() in all possible code paths after an acquire(), and so on.

NOTE: If you are using the lock just to keep the screen on, you should
strongly consider using FLAG_KEEP_SCREEN_ON instead. This window flag will be
correctly managed by the platform as the user moves between applications and
doesn't require a special permission. See
http://developer.android.com/reference/android/view/WindowManager.LayoutParams
html#FLAG_KEEP_SCREEN_ON.
```

Also see [wakelock's javadoc](https://developer.android.com/reference/android/os/PowerManager.WakeLock.html).

### PR DESCRIPTION
**Pull request by luiscruz**
This closes #206 - New Refactoring - Android - Wakelock.

### CODE REVIEW

File: samples/src/test/java/org/autorefactor/refactoring/rules/samples_in/WakeLockSample.java [hunk 1]
```diff
@@ -0,0 +1,86 @@
+package org.autorefactor.refactoring.rules.samples_in;
+import android.app.Activity;
```
Comment (JnRouvignac) [inline samples/src/test/java/org/autorefactor/refactoring/rules/samples_in/WakeLockSample.java]: Add a new line before import please.
Please add copyright notices.

File: samples/src/test/java/org/autorefactor/refactoring/rules/samples_out/WakeLockSample.java [hunk 2]
```diff
@@ -0,0 +1,104 @@
+package org.autorefactor.refactoring.rules.samples_out;
+import android.app.Activity;
```
Comment (JnRouvignac) [inline samples/src/test/java/org/autorefactor/refactoring/rules/samples_out/WakeLockSample.java]: Add a new line before import please.
Please add copyright notices.

File: samples/src/test/java/org/autorefactor/refactoring/rules/samples_in/WakeLockSample.java [hunk 3]
```diff
@@ -0,0 +1,86 @@
...
+import android.os.PowerManager;
+import android.os.PowerManager.WakeLock;
+
+public class WakeLockSample {
+	public class SimpleWakeLockActivity extends Activity {
+		private PowerManager.WakeLock wl;
+		
+		@Override
+		protected void onCreate(Bundle savedInstanceState) {
+			// TODO Auto-generated method stub
```
Comment (JnRouvignac) [inline samples/src/test/java/org/autorefactor/refactoring/rules/samples_in/WakeLockSample.java]: Please remove this useless comment.

File: samples/src/test/java/org/autorefactor/refactoring/rules/samples_in/WakeLockSample.java [hunk 4]
```diff
@@ -0,0 +1,86 @@
...
+			super.onDestroy();
+		}
+	}
+	
+	public class SimpleWakeLockWithoutOnPauseActivity extends Activity {
+		private PowerManager.WakeLock wl;
+		
+		@Override
+		protected void onCreate(Bundle savedInstanceState) {
+			// TODO Auto-generated method stub
```
Comment (JnRouvignac) [inline samples/src/test/java/org/autorefactor/refactoring/rules/samples_in/WakeLockSample.java]: Please remove all such useless comments.

File: plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java [hunk 5]
```diff
@@ -0,0 +1,208 @@
...
+import org.eclipse.jdt.core.dom.TypeDeclaration;
+import org.eclipse.jdt.core.dom.rewrite.ASTRewrite;
+import org.eclipse.jdt.internal.corext.dom.ASTNodes;
+
+/** See {@link #getDescription()} method. */
+public class WakeLockRefactoring extends AbstractRefactoringRule {
+
+    @Override
+    public String getDescription() {
+        // TODO Auto-generated method stub
```
Comment (JnRouvignac) [inline plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java]: Please remove.

File: plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java [hunk 6]
```diff
@@ -0,0 +1,208 @@
...
+    }
+
+    @Override
+    public boolean visit(MethodInvocation node) {
+        if (isMethod(node, "android.os.PowerManager.WakeLock", "release")) {
+            // check whether it is being called in onDestroy
+            final Refactorings r = this.ctx.getRefactorings();
+            final ASTBuilder b = this.ctx.getASTBuilder();
+            MethodDeclaration enclosingMethod;
+            enclosingMethod = (MethodDeclaration) ASTNodes.getParent(node, ASTNode.METHOD_DECLARATION);
```
Comment (JnRouvignac) [inline plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java]: Use static imports for all accesses to `ASTNode` fields.

Comment (JnRouvignac) [inline plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java]: Please join variable declaration and initialization.

Comment (JnRouvignac) [inline plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java]: And use `ASTHelper.getAncestor()`:
```java
            MethodDeclaration enclosingMethod = getAncestor(node, MethodDeclaration.class);
```

File: plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java [hunk 7]
```diff
@@ -0,0 +1,208 @@
...
+            if (isMethod(enclosingMethod.resolveBinding(), "android.app.Activity", "onDestroy")) {
```
Comment (JnRouvignac) [inline plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java]: I think it is more readable if you create `ASTHelper.isMethod(MethodDeclaration, ....)` like this:

```java
    public static boolean isMethod(MethodDeclaration node, String typeQualifiedName,
            String methodName, String... parameterTypesQualifiedNames) {
        return node != null
                && isMethod(node.resolveBinding(), typeQualifiedName, methodName, parameterTypesQualifiedNames);
    }
```

Make sure you insert it above `    public static boolean isMethod(IMethodBinding, ...)`

File: plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java [hunk 8]
```diff
@@ -0,0 +1,208 @@
...
+        MethodInvocation isHeldInvocation = b.getAST().newMethodInvocation();
+        isHeldInvocation.setName(b.simpleName("isHeld"));
+        isHeldInvocation.setExpression(b.copyExpression(methodInvocation));
+        prefixExpression.setOperand(isHeldInvocation);
+        ifStatement.setExpression(prefixExpression);
+        // then
+        MethodInvocation releaseInvocation = b.getAST().newMethodInvocation();
+        releaseInvocation.setName(b.simpleName("release"));
+        releaseInvocation.setExpression(b.copyExpression(methodInvocation));
+        ExpressionStatement releaseExpressionStatement = b.getAST().newExpressionStatement(releaseInvocation);
```
Comment (JnRouvignac) [inline plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java]:
```java
        MethodInvocation releaseInvocation = b.getAST().newMethodInvocation();
        releaseInvocation.setName(b.simpleName("release"));
        releaseInvocation.setExpression(b.copyExpression(methodInvocation));
```
=>
```java
        MethodInvocation releaseInvocation = b.invoke(b.copyExpression(methodInvocation), "release");
```
And you need to create `ASTBuilder.invoke(Expression, String, Expression... arguments)`

File: plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java [hunk 9]
```diff
@@ -0,0 +1,208 @@
...
+                            typeDeclaration.getBodyDeclarationsProperty(),
+                            typeDeclaration);
+                    return DO_NOT_VISIT_SUBTREE;
+                }
+            }
+        }
+        return VISIT_SUBTREE;
+    }
+
+    private Statement createWakelockReleaseNode(MethodInvocation methodInvocation) {
```
Comment (JnRouvignac) [inline plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java]: What do you think of this?

```java
    private Statement createWakelockReleaseNode(MethodInvocation methodInvocation) {
         final ASTBuilder b = ctx.getASTBuilder();
         return b.if0(
             b.not(b.invoke(b.copyExpression(methodInvocation), "isHeld"))),
             b.block(b.toStmt(b.invoke(b.copyExpression(methodInvocation), "release"))));
```

File: plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java [hunk 10]
```diff
@@ -0,0 +1,208 @@
...
+        onPauseDeclaration.modifiers().add(annotation);
+        //
+        Modifier protectedModifier = b.getAST().newModifier(ModifierKeyword.PROTECTED_KEYWORD);
+        onPauseDeclaration.modifiers().add(protectedModifier);
+        //
+        SuperMethodInvocation superMethodInvocation = b.getAST().newSuperMethodInvocation();
+        superMethodInvocation.setName(b.simpleName("onPause"));
+
+        //
+        ASTRewrite rewriter = ASTRewrite.create(b.getAST());
```
Comment (JnRouvignac) [inline plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java]: Unused, please remove.

File: plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java [hunk 11]
```diff
@@ -0,0 +1,208 @@
...
+                MethodDeclaration onPauseDeclaration = createOnPauseDeclaration();
+
+                // add onPause declaration to the Activity
+                r.insertAfter(onPauseDeclaration, enclosingMethod);
+                return DO_NOT_VISIT_SUBTREE;
+            }
+        } else if (isMethod(node, "android.os.PowerManager.WakeLock", "acquire")) {
+            final Refactorings r = this.ctx.getRefactorings();
+            final ASTBuilder b = this.ctx.getASTBuilder();
+            TypeDeclaration typeDeclaration = (TypeDeclaration) ASTNodes.getParent(node, ASTNode.TYPE_DECLARATION);
```
Comment (JnRouvignac) [inline plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java]: Use `getAncestor()`

File: plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java [hunk 12]
```diff
@@ -0,0 +1,208 @@
...
+        ASTRewrite rewriter = ASTRewrite.create(b.getAST());
+        Block block = b.block(
+                b.newlinePlaceholder(),
+                b.getAST().newExpressionStatement(superMethodInvocation),
+                b.newlinePlaceholder());
+        onPauseDeclaration.setBody(block);
+        return onPauseDeclaration;
+    }
+
+    private MethodDeclaration findMethodOfType(String methodToFind,
```
Comment (JnRouvignac) [inline plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java]: Proposed implementation (note the name change and signature change):
```java
    private MethodDeclaration findMethod(TypeDeclaration typeDeclaration, String methodName) {
        ITypeBinding typeBinding = typeDeclaration.resolveBinding();
        if (typeBinding != null) {
            for (IMethodBinding method : typeBinding.getDeclaredMethods()) {
                if (methodName.equals(method.getName()) && method.getParameterTypes().length == 0) {
                    return method;
                }
            }
        }
        return null;
    }
```

File: plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java [hunk 13]
```diff
@@ -0,0 +1,208 @@
...
+        return null;
+    }
+
+
+    private class ReleasePresenceChecker extends ASTVisitor {
+        private boolean releasePresent = false;
+        public boolean isReleasePresent() {
+            return releasePresent;
+        }
+        @Override
```
Comment (JnRouvignac) [inline plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java]: Please insert empty line before annotation

File: plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java [hunk 14]
```diff
@@ -0,0 +1,208 @@
...
+                return method;
+            }
+        }
+        return null;
+    }
+
+
+    private class ReleasePresenceChecker extends ASTVisitor {
+        private boolean releasePresent = false;
+        public boolean isReleasePresent() {
```
Comment (JnRouvignac) [inline plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java]: Pleae inline this method since this in ner class is local to this refactoring rule.

File: plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java [hunk 15]
```diff
@@ -0,0 +1,208 @@
...
+                Statement releaseNode = createWakelockReleaseNode(node);
+                MethodDeclaration onPauseMethod = findMethodOfType("onPause", typeDeclaration);
+                if (onPauseMethod != null && node.getParent().getNodeType() == ASTNode.EXPRESSION_STATEMENT) {
+                    r.insertAt(releaseNode,
+                            onPauseMethod.getBody().statements().size(),
+                            Block.STATEMENTS_PROPERTY,
+                            onPauseMethod.getBody());
+                    return DO_NOT_VISIT_SUBTREE;
+                } else {
+                    MethodDeclaration onPauseDeclaration = createOnPauseDeclaration();
```
Comment (JnRouvignac) [inline plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java]: Please inline this variable.

File: plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java [hunk 16]
```diff
@@ -0,0 +1,208 @@
...
+                return DO_NOT_VISIT_SUBTREE;
+            }
+        } else if (isMethod(node, "android.os.PowerManager.WakeLock", "acquire")) {
+            final Refactorings r = this.ctx.getRefactorings();
+            final ASTBuilder b = this.ctx.getASTBuilder();
+            TypeDeclaration typeDeclaration = (TypeDeclaration) ASTNodes.getParent(node, ASTNode.TYPE_DECLARATION);
+            ReleasePresenceChecker releasePresenceChecker = new ReleasePresenceChecker();
+            typeDeclaration.accept(releasePresenceChecker);
+            if (!releasePresenceChecker.releasePresent) {
+                Statement releaseNode = createWakelockReleaseNode(node);
```
Comment (JnRouvignac) [inline plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java]: Please reduce scope of variable

File: plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java [hunk 17]
```diff
@@ -0,0 +1,208 @@
...
+                    r.insertAt(releaseNode,
+                            onPauseMethod.getBody().statements().size(),
+                            Block.STATEMENTS_PROPERTY,
+                            onPauseMethod.getBody());
+                    return DO_NOT_VISIT_SUBTREE;
+                } else {
+                    MethodDeclaration onPauseDeclaration = createOnPauseDeclaration();
+                    /* TODO @JnRouvignac, instead of using insertAt, calling
+                     * typeDeclaration.bodyDeclarations().add(onPauseDeclaration);
+                     * would be more intuitive.
```
Comment (JnRouvignac) [inline plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java]: I agree, that sucks. `r.insertLast()` would suck less, but it still sucks.

File: plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java (hunk 6 above)
Comment (luiscruz) [inline plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java]: oh this is cool! 😅

Comment (JnRouvignac) [inline plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java]: yes

File: plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java [hunk 18]
```diff
@@ -0,0 +1,208 @@
...
+        // then
+        MethodInvocation releaseInvocation = b.getAST().newMethodInvocation();
+        releaseInvocation.setName(b.simpleName("release"));
+        releaseInvocation.setExpression(b.copyExpression(methodInvocation));
+        ExpressionStatement releaseExpressionStatement = b.getAST().newExpressionStatement(releaseInvocation);
+        ifStatement.setThenStatement(b.block(releaseExpressionStatement));
+        return ifStatement;
+    }
+
+    private MethodDeclaration createOnPauseDeclaration() {
```
Comment (JnRouvignac) [inline plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java]: And `ASTBuilder.annotation()` should use `MarkerAnnotation` instead of `NormalAnnotation`.

File: plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java (hunk 7 above)
Comment (JnRouvignac) [inline plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java]: Actually I have just merged this change (along with another change useful to you).
Please rebase.

File: plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java [hunk 19]
```diff
@@ -0,0 +1,208 @@
...
+            if (methodBinding != null
+                    && methodToFind.equals(methodBinding.getName())) {
+                return method;
+            }
+        }
+        return null;
+    }
+
+
+    private class ReleasePresenceChecker extends ASTVisitor {
```
Comment (JnRouvignac) [inline plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java]: Also please extend the new `FinderVisitor`.

File: plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java (hunk 9 above)
Comment (luiscruz) [inline plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java]: this is great :)

File: plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java (hunk 8 above)
Comment (luiscruz) [inline plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java]: > And you need to create ASTBuilder.invoke(Expression, String, Expression... arguments)
What do you mean?

Comment (JnRouvignac) [inline plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java]: Forget that sentence, this method already exists.
I badly read the code.

File: plugin/src/main/java/org/autorefactor/refactoring/Refactorings.java [hunk 20]
```diff
@@ -413,4 +413,13 @@ public BadLocationException call() throws Exception {
             throw ex;
         }
     }
+
+    /**
+     * Gets the ASTRewrite rewrite object.
+     *
+     * @return the ASTRewrite rewrite
+     */
+    public ASTRewrite getRewrite() {
```
Comment (luiscruz) [inline plugin/src/main/java/org/autorefactor/refactoring/Refactorings.java]: I needed this to create newlines inside ```ASTBuilder``` (```Statement newlinePlaceholder()```). I couldn't find an approach that did not use it ```rewrite```.

Comment (JnRouvignac) [inline plugin/src/main/java/org/autorefactor/refactoring/Refactorings.java]: I know :)
I will try to see if we can otherwise once the rest of the code is clearer to me.

File: samples/src/test/java/org/autorefactor/refactoring/rules/samples_in/WakeLockSample.java [hunk 21]
```diff
@@ -0,0 +1,86 @@
...
+	public class SimpleWakeLockActivity extends Activity {
+		private PowerManager.WakeLock wl;
+		
+		@Override
+		protected void onCreate(Bundle savedInstanceState) {
+			// TODO Auto-generated method stub
+			super.onCreate(savedInstanceState);
+
+			PowerManager pm = (PowerManager)this.getSystemService(Context.POWER_SERVICE);
+			WakeLock wl = pm.newWakeLock(PowerManager.SCREEN_DIM_WAKE_LOCK | PowerManager.ON_AFTER_RELEASE, "WakeLockSample");
```
Comment (JnRouvignac) [inline samples/src/test/java/org/autorefactor/refactoring/rules/samples_in/WakeLockSample.java]: This shadows the `wl` field. Is it intended?

File: samples/src/test/java/org/autorefactor/refactoring/rules/samples_in/WakeLockSample.java [hunk 22]
```diff
@@ -0,0 +1,86 @@
...
+	public class SimpleWakeLockWithoutReleaseActivity extends Activity {
+		private PowerManager.WakeLock wl;
+		
+		@Override
+		protected void onCreate(Bundle savedInstanceState) {
+			// TODO Auto-generated method stub
+			super.onCreate(savedInstanceState);
+
+			PowerManager pm = (PowerManager)this.getSystemService(Context.POWER_SERVICE);
+			WakeLock wl = pm.newWakeLock(PowerManager.SCREEN_DIM_WAKE_LOCK | PowerManager.ON_AFTER_RELEASE, "WakeLockSample");
```
Comment (JnRouvignac) [inline samples/src/test/java/org/autorefactor/refactoring/rules/samples_in/WakeLockSample.java]: This shadows the `wl` field. Is it intended?

File: plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java (hunk 12 above)
Comment (luiscruz) [inline plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java]: This does not return a ```MethodDeclaration``` object. How can I get from the ```IMethodBinding```?

Comment (JnRouvignac) [inline plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java]: Oh crap I missed that

File: plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java (hunk 16 above)
Comment (luiscruz) [inline plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java]: You mean inline variable ```releaseNode```?

File: plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java (hunk 17 above)
Comment (luiscruz) [inline plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java]: Should I create ```insertLast()```?

File: plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java [hunk 23]
```diff
@@ -0,0 +1,208 @@
...
+import org.eclipse.jdt.core.dom.NormalAnnotation;
+import org.eclipse.jdt.core.dom.PrefixExpression;
+import org.eclipse.jdt.core.dom.Statement;
+import org.eclipse.jdt.core.dom.SuperMethodInvocation;
+import org.eclipse.jdt.core.dom.TypeDeclaration;
+import org.eclipse.jdt.core.dom.rewrite.ASTRewrite;
+import org.eclipse.jdt.internal.corext.dom.ASTNodes;
+
+/** See {@link #getDescription()} method. */
+public class WakeLockRefactoring extends AbstractRefactoringRule {
```
Comment (luiscruz) [inline plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java]: Good idea!

File: plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java (hunk 12 above)
Comment (JnRouvignac) [inline plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java]: So just inline variable `methods`

File: plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java (hunk 16 above)
Comment (JnRouvignac) [inline plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java]: Yes

File: samples/src/test/java/org/autorefactor/refactoring/rules/samples_in/WakeLockSample.java (hunk 21 above)
Comment (luiscruz) [inline samples/src/test/java/org/autorefactor/refactoring/rules/samples_in/WakeLockSample.java]: No, it's not intended 👎 good point!

File: plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java (hunk 16 above)
Comment (JnRouvignac) [inline plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java]: This is what I mean: http://refactoring.com/catalog/reduceScopeOfVariable.html

File: plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java (hunk 17 above)
Comment (JnRouvignac) [inline plugin/src/main/java/org/autorefactor/refactoring/rules/WakeLockRefactoring.java]: Yes let's do that first and see how much it helps.
You can use http://help.eclipse.org/neon/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2Fdom%2Frewrite%2FListRewrite.html underneath

File: plugin/src/main/java/org/autorefactor/refactoring/ASTBuilder.java [hunk 24]
```diff
@@ -857,4 +864,37 @@ public Expression parenthesizeIfNeeded(Expression expr) {
...
+    public Modifier modifierProtected() {
+        return getAST().newModifier(ModifierKeyword.PROTECTED_KEYWORD);
+    }
+
+    public List<IExtendedModifier> modifiers(IExtendedModifier... modifiers) {
+        return Arrays.asList(modifiers);
+    }
+
+    public Expression superInvoke(String methodName) {
+        SuperMethodInvocation superMethodInvocation = getAST().newSuperMethodInvocation();
```
Comment (JnRouvignac) [inline plugin/src/main/java/org/autorefactor/refactoring/ASTBuilder.java]: `superMethodInvocation` => `smi`
THe shorter the method, the shorter the variable name

File: plugin/src/main/java/org/autorefactor/refactoring/ASTBuilder.java [hunk 25]
```diff
@@ -857,4 +864,37 @@ public Expression parenthesizeIfNeeded(Expression expr) {
...
+        superMethodInvocation.setName(simpleName(methodName));
+        return superMethodInvocation;
+    }
+
+    public MethodDeclaration method(List<IExtendedModifier> modifiers, String methodName, List<SingleVariableDeclaration> parameters,
+            Block block) {
+        MethodDeclaration methodDeclaration = getAST().newMethodDeclaration();
```
Comment (JnRouvignac) [inline plugin/src/main/java/org/autorefactor/refactoring/ASTBuilder.java]: likewise `methodDeclaration` => `md`

File: plugin/src/main/java/org/autorefactor/refactoring/Refactorings.java (hunk 20 above)
Comment (luiscruz) [inline plugin/src/main/java/org/autorefactor/refactoring/Refactorings.java]: Yea, Eclipse added the rest of the code automatically. Different standards :P

File: plugin/src/main/java/org/autorefactor/refactoring/ASTBuilder.java (hunk 24 above)
Comment (luiscruz) [inline plugin/src/main/java/org/autorefactor/refactoring/ASTBuilder.java]: This is a personal standard, right? IMO clear variable names help read the code and writing the code is quite the same when using autocomplete. (my 2 cents 😄)

File: plugin/src/main/java/org/autorefactor/refactoring/rules/AndroidWakeLockRefactoring.java [hunk 26]
```diff
@@ -0,0 +1,178 @@
...
+    @Override
+    public boolean visit(MethodInvocation node) {
+        if (isMethod(node, "android.os.PowerManager.WakeLock", "release")) {
+            // check whether it is being called in onDestroy
+            final Refactorings r = this.ctx.getRefactorings();
+            final ASTBuilder b = this.ctx.getASTBuilder();
+            MethodDeclaration enclosingMethod = getAncestor(node, MethodDeclaration.class);
+            if (isMethod(enclosingMethod.resolveBinding(), "android.app.Activity", "onDestroy")) {
+                TypeDeclaration typeDeclaration;
+                typeDeclaration = getAncestor(enclosingMethod, TypeDeclaration.class);
```
Comment (JnRouvignac) [inline plugin/src/main/java/org/autorefactor/refactoring/rules/AndroidWakeLockRefactoring.java]: Please join declaration:

```java
                TypeDeclaration typeDeclaration = getAncestor(enclosingMethod, TypeDeclaration.class);
```

File: plugin/src/main/java/org/autorefactor/refactoring/rules/AndroidWakeLockRefactoring.java [hunk 27]
```diff
@@ -0,0 +1,178 @@
...
+    @Override
+    public String getName() {
+        return "Android WakeLock";
+    }
+
+    @Override
+    public boolean visit(MethodInvocation node) {
+        if (isMethod(node, "android.os.PowerManager.WakeLock", "release")) {
+            // check whether it is being called in onDestroy
+            final Refactorings r = this.ctx.getRefactorings();
```
Comment (JnRouvignac) [inline plugin/src/main/java/org/autorefactor/refactoring/rules/AndroidWakeLockRefactoring.java]: Please reduce scope of variable.

File: plugin/src/main/java/org/autorefactor/refactoring/rules/AndroidWakeLockRefactoring.java [hunk 28]
```diff
@@ -0,0 +1,178 @@
...
+        } else if (isMethod(node, "android.os.PowerManager.WakeLock", "acquire")) {
+            final Refactorings r = this.ctx.getRefactorings();
+            final ASTBuilder b = this.ctx.getASTBuilder();
+            TypeDeclaration typeDeclaration = getAncestor(node, TypeDeclaration.class);
+            ReleasePresenceChecker releasePresenceChecker = new ReleasePresenceChecker();
+            if (!releasePresenceChecker.findOrDefault(typeDeclaration, false)) {
+                Statement releaseNode = createWakelockReleaseNode(node);
+                MethodDeclaration onPauseMethod = findMethod(typeDeclaration, "onPause");
+                if (onPauseMethod != null && node.getParent().getNodeType() == ASTNode.EXPRESSION_STATEMENT) {
+                    r.insertAt(releaseNode,
```
Comment (JnRouvignac) [inline plugin/src/main/java/org/autorefactor/refactoring/rules/AndroidWakeLockRefactoring.java]: Use `Refactorings.insertLast()` instead?

File: plugin/src/main/java/org/autorefactor/refactoring/rules/AndroidWakeLockRefactoring.java [hunk 29]
```diff
@@ -0,0 +1,178 @@
...
+                            Block.STATEMENTS_PROPERTY,
+                            onPauseMethod.getBody());
+                    return DO_NOT_VISIT_SUBTREE;
+                } else {
+                    MethodDeclaration onPauseDeclaration = createOnPauseMethodDeclaration();
+                    /* TODO @JnRouvignac, instead of using insertAt, calling
+                     * typeDeclaration.bodyDeclarations().add(onPauseDeclaration);
+                     * would be more intuitive.
+                     */
+                    r.insertAt(
```
Comment (JnRouvignac) [inline plugin/src/main/java/org/autorefactor/refactoring/rules/AndroidWakeLockRefactoring.java]: Use `Refactorings.insertLast()` instead?

File: plugin/src/main/java/org/autorefactor/refactoring/Refactorings.java (hunk 20 above)
Comment (JnRouvignac) [inline plugin/src/main/java/org/autorefactor/refactoring/Refactorings.java]: No, I think you used "Encapsulate Field" refactoring because this is exactly the result you would get in this case.

File: plugin/src/main/java/org/autorefactor/refactoring/ASTBuilder.java (hunk 24 above)
Comment (JnRouvignac) [inline plugin/src/main/java/org/autorefactor/refactoring/ASTBuilder.java]: I do not think I am the only one.
I have some references to point out:
http://www.itiseezee.com/?p=83

> The length of a name should correspond to the size of its scope.
> Single-letter names should ONLY be used as local variables inside short methods.

Of course you may use other advices in this web page to counteract what I am saying :)

&nbsp;


I am always in favour of descriptive names.
However here I do not think the long name adds any value. I get bored before I can read the whole `superMethodInvocation`, and I can easily remember that `smi` is shorthand for `superMethodInvocation` in these 3 lines of code. I am even tempted to just name this variable `result` :)

&nbsp;

I can show you places where I have chosen very long names and I will not change them because this long name helps make the code more readable IMO:
https://github.com/JnRouvignac/AutoRefactor/blob/master/plugin/src/main/java/org/autorefactor/refactoring/ASTHelper.java#L1443

&nbsp;

Anyway, this is my POV, you may disagree :)

File: plugin/src/main/java/org/autorefactor/refactoring/rules/AndroidWakeLockRefactoring.java [hunk 30]
```diff
@@ -0,0 +1,178 @@
...
+                /* If it reaches this part of the code, it
+                 * means it did not find onPause method in the class.
+                 */
+                // add onPause declaration to the Activity
+                r.insertAfter(createOnPauseMethodDeclaration(), enclosingMethod);
+                return DO_NOT_VISIT_SUBTREE;
+            }
+        } else if (isMethod(node, "android.os.PowerManager.WakeLock", "acquire")) {
+            final Refactorings r = this.ctx.getRefactorings();
+            final ASTBuilder b = this.ctx.getASTBuilder();
```
Comment (luiscruz) [inline plugin/src/main/java/org/autorefactor/refactoring/rules/AndroidWakeLockRefactoring.java]: check

File: plugin/src/main/java/org/autorefactor/refactoring/Refactorings.java [hunk 31]
```diff
@@ -413,4 +418,40 @@ public BadLocationException call() throws Exception {
...
+     * @param declaration the declaration to be added
+     * @param td the type declaration
+     */
+    public void insertLast(BodyDeclaration declaration, TypeDeclaration td) {
+        insertAt(
+                declaration,
+                td.bodyDeclarations().size(),
+                td.getBodyDeclarationsProperty(),
+                td);
+    }
```
Comment (JnRouvignac) [inline plugin/src/main/java/org/autorefactor/refactoring/Refactorings.java]: This is not what I expected :)

I am trying to write code as generic as possible here.
These two methods are very specific.

I was more expecting something like this:
```java
    public void insertLast(ASTNode nodeToInsert, StructuralPropertyDescriptor locationInParent, ASTNode listHolder) {
        getListRewrite(listHolder, locationInParent).insertLast(nodeToInsert, null);
        addRefactoredNodes(listHolder);
    }
```
I am going to commit such method anyway because we will certainly need them in the future.

That being said I can see where you are going and it makes sense to me.
I am considering my options for handling this :)

Comment (JnRouvignac) [inline plugin/src/main/java/org/autorefactor/refactoring/Refactorings.java]: Please make use of the new `Refactorings.insertLast()` and either:
1. remove these specific methods
2. or move them back to `AndroidWakeLockRefactoring`.

File: plugin/src/main/java/org/autorefactor/refactoring/rules/AndroidWakeLockRefactoring.java [hunk 32]
```diff
@@ -0,0 +1,152 @@
...
+                // add onPause declaration to the Activity
+                r.insertAfter(createOnPauseMethodDeclaration(), enclosingMethod);
+                return DO_NOT_VISIT_SUBTREE;
+            }
+        } else if (isMethod(node, "android.os.PowerManager.WakeLock", "acquire")) {
+            final Refactorings r = this.ctx.getRefactorings();
+            TypeDeclaration typeDeclaration = getAncestor(node, TypeDeclaration.class);
+            ReleasePresenceChecker releasePresenceChecker = new ReleasePresenceChecker();
+            if (!releasePresenceChecker.findOrDefault(typeDeclaration, false)) {
+                Statement releaseNode = createWakelockReleaseNode(node);
```
Comment (JnRouvignac) [inline plugin/src/main/java/org/autorefactor/refactoring/rules/AndroidWakeLockRefactoring.java]: Please reduce scope of `releaseNode` local variable. :)

i.e.e move it in the if statement just before where it is used.

File: plugin/src/main/java/org/autorefactor/refactoring/rules/AndroidWakeLockRefactoring.java [hunk 33]
```diff
@@ -0,0 +1,152 @@
...
+                MethodDeclaration onPauseMethod = findMethod(typeDeclaration, "onPause");
+                if (onPauseMethod != null && node.getParent().getNodeType() == ASTNode.EXPRESSION_STATEMENT) {
+                    r.insertLast(releaseNode, onPauseMethod);
+                    return DO_NOT_VISIT_SUBTREE;
+                } else {
+                    MethodDeclaration onPauseDeclaration = createOnPauseMethodDeclaration();
+                    /* TODO @JnRouvignac, instead of using insertAt, calling
```
Comment (JnRouvignac) [inline plugin/src/main/java/org/autorefactor/refactoring/rules/AndroidWakeLockRefactoring.java]: I believe this comment is now outdated.
Please remove it.

File: plugin/src/main/java/org/autorefactor/refactoring/rules/AndroidWakeLockRefactoring.java [hunk 34]
```diff
@@ -0,0 +1,152 @@
...
+            TypeDeclaration typeDeclaration = getAncestor(node, TypeDeclaration.class);
+            ReleasePresenceChecker releasePresenceChecker = new ReleasePresenceChecker();
+            if (!releasePresenceChecker.findOrDefault(typeDeclaration, false)) {
+                Statement releaseNode = createWakelockReleaseNode(node);
+                MethodDeclaration onPauseMethod = findMethod(typeDeclaration, "onPause");
+                if (onPauseMethod != null && node.getParent().getNodeType() == ASTNode.EXPRESSION_STATEMENT) {
+                    r.insertLast(releaseNode, onPauseMethod);
+                    return DO_NOT_VISIT_SUBTREE;
+                } else {
+                    MethodDeclaration onPauseDeclaration = createOnPauseMethodDeclaration();
```
Comment (JnRouvignac) [inline plugin/src/main/java/org/autorefactor/refactoring/rules/AndroidWakeLockRefactoring.java]: Please inline `onPauseDeclaration` variable.

File: samples/src/test/java/org/autorefactor/refactoring/rules/samples_in/AndroidWakeLockSample.java [hunk 35]
```diff
@@ -0,0 +1,115 @@
...
+            super.onDestroy();
+        }
+    }
+
+    public class SimpleWakeLockWithoutOnPauseActivity extends Activity {
+        private WakeLock wl;
+
+        @Override
+        protected void onCreate(Bundle savedInstanceState) {
+            // TODO Auto-generated method stub
```
Comment (JnRouvignac) [inline samples/src/test/java/org/autorefactor/refactoring/rules/samples_in/AndroidWakeLockSample.java]: Please remove all such comments

File: plugin/src/main/java/org/autorefactor/refactoring/rules/AndroidWakeLockRefactoring.java [hunk 36]
```diff
@@ -0,0 +1,152 @@
...
+    public boolean visit(MethodInvocation node) {
+        if (isMethod(node, "android.os.PowerManager.WakeLock", "release")) {
+            // check whether it is being called in onDestroy
+            MethodDeclaration enclosingMethod = getAncestor(node, MethodDeclaration.class);
+            if (isMethod(enclosingMethod.resolveBinding(), "android.app.Activity", "onDestroy")) {
+                final Refactorings r = this.ctx.getRefactorings();
+                TypeDeclaration typeDeclaration = getAncestor(enclosingMethod, TypeDeclaration.class);
+                MethodDeclaration onPauseMethod = findMethod(typeDeclaration, "onPause");
+                if (onPauseMethod != null && node.getParent().getNodeType() == ASTNode.EXPRESSION_STATEMENT) {
+                    r.remove(node.getParent());
```
Comment (JnRouvignac) [inline plugin/src/main/java/org/autorefactor/refactoring/rules/AndroidWakeLockRefactoring.java]: What is the parent node? What do you expect to remove here?
That seems risky to removing something without checking what it is.

Comment (luiscruz) [inline plugin/src/main/java/org/autorefactor/refactoring/rules/AndroidWakeLockRefactoring.java]: Basically we are removing ```wakelock.realese()``` from ```onDestroy()``` method and we put it on ```onUpdate()```

**Comment by luiscruz** [comment]
Thanks! 👍
